Remove old key, add new key, revise travis decrypt
Sage-Bionetworks/agora-data-manager pull request #16
Opened 2020-07-10 19:14 UTC by ahayden

This PR deploys a new ssh key to the repo that can be decrypted and used by the travis job

2020-07-10 19:53 UTC, zaro0508 reviewed
this depends on deploying a new instance so please add a `depends on` in the PR message.

2020-07-10 19:53 UTC, zaro0508 commented on .travis.yml
> +  - openssl aes-256-cbc -K $encrypted_8b76707d972e_key -iv $encrypted_8b76707d972e_iv -in agora-travis.pem.enc -out agora-travis.pem -d
please remember to remove the old *_key and *_iv from travis settings.

2020-07-10 20:15 UTC, ahayden commented
I think the dependency is more like the instance rebuild (https://github.com/Sage-Bionetworks/Agora-infra/pull/82) depends on this one.

2020-07-14 16:31 UTC, zaro0508 requested changes
the updatedb.sh file references `toptal_org-sagebase-scicomp.pem` as well.  need to update those to new files.

2020-07-14 17:55 UTC, zaro0508 requested changes

2020-07-14 17:55 UTC, zaro0508 commented on .travis.yml
> +  - openssl aes-256-cbc -K $encrypted_8b76707d972e_key -iv $encrypted_8b76707d972e_iv -in agora-travis.pem.enc -out agora-travis.pem -d
this should be using the agora-access key to access the DB instance

2020-07-14 18:02 UTC, zaro0508 commented
replacing this PR with PR #17

2020-07-14 18:02 UTC, closed without merging